#!/bin/sh
case $(uname) in
    Darwin)
        OS="Darwin"
        ;;
    Linux)
        if command -v pacman >/dev/null 2>&1;then
            OS="Arch"
        elif command -v dnf >/dev/null 2>&1;then
            OS="Fedora"
        elif command -v apt-get >/dev/null 2>&1;then
            OS="Ubuntu"
        fi
        ;;
    *)
        echo "Not support your OS!"
        exit 1
esac

##Install dev tools
cd dev
case "$OS" in
    "Arch")
        sudo /bin/bash dev-arch
        ;;
    "Fedora")
        sudo /bin/bash dev-fedora
        ;;
    "Ubuntu")
        sudo /bin/bash dev-ubuntu
        ;;
esac
cd -

##Set proxy
read -p "Set proxy?[Y/n]" setProxy
if [[ "$setProxy"!=[nN] ]];then
    if [ ! -e /usr/local/bin/ss-client ];then
        echo "Error: Can't find ss-client!"
        exit 1
    fi
    sudo /usr/local/bin/ss-client globalRestart
    if netstat -tan |grep -q 8118;then
        export http_proxy=127.0.0.1:8118
        export HTTP_PROXY=127.0.0.1:8118
        export https_proxy=127.0.0.1:8118
        export HTTPS_PROXY=127.0.0.1:8118
    else
        echo "Error ss-client start error: can not find listen port on 8118"
        exit 1
    fi
fi
##Set git
cd git
/bin/bash setGit
cd -

##Set docker
cd docker
case "$OS" in
    "Arch")
        /bin/bash docker-arch
        ;;
esac
cd -

##Set golang
cd golang
/bin/bash setGolang
cd -

##Set shell
cd shell
/bin/bash 10-zsh-installer.sh
/bin/bash 20-set-zsh-theme.sh
/bin/bash 30-config-shell.sh install
cd -

##Service
cd service
case "$OS" in
    "Arch")
        /bin/bash arch-rc-local-service.sh
        ;;
esac
cd -

##Set vim
cd supervim
/bin/bash install.sh install
cd -
