#!/bin/bash
if ! command -v pacman >/dev/null 2>&1;then
    echo "Error: Not archlinux!"
    exit 1
fi
if [[ $EUID != 0 ]];then
    echo "Error:need root priviledge!"
    exit 1
fi

archApps="base-devel linux-headers clang neovim vim git openssh net-tools cmake python tree boost python-pip go go-tools fontconfig ctags screenfetch wget cronie unzip  zsh zsh-syntax-highlighting"

pacman -Syu --noconfirm --needed
for tool in ${archApps};do
    pacman -S $tool --noconfirm --needed
done

if dmesg | grep -iq hypervisor;then
    if dmesg | grep -iq vbox;then
        echo "Running on VirtualBox,installing virtualbox-guest-utils..."
        pacman -S virtualbox-guest-utils --noconfirm --needed
    fi
fi

systemctl enable sshd
systemctl enable dhcpcd
systemctl enable cronie

read -p "Install Desktop Environment? [y/N] " -t 5 de
if [[ "$de" == [yY] ]];then
    while read -p "Install which display manager ?[lxdm or sddm ] " dm;do
        if echo $dm | grep -P '^(lxdm|sddm)$';then
            echo "$dm will be installed"
            break
        else
            echo "Input error, try again!"
        fi
    done

    #the basis of all DE
    pacman -S xorg --noconfirm --needed
    pacman -S xorg-xinit --noconfirm --needed
    #install dm 
    pacman -S "$dm" --noconfirm --needed
    systemctl enable "$dm"

    pacman -S adobe-source-han-sans-cn-fonts --noconfirm  -needed
    pacman -S gnome-terminal --noconfirm  --needed
    read -p "Install lxde ?(Y/n) " lxde
    if [[ "$lxde" != [nN] ]];then
        #安装lxde桌面环境相关
        pacman -S lxde-common --noconfirm --needed
        pacman -S lxsession --noconfirm --needed
        pacman -S lxpanel --noconfirm --needed
        pacman -S openbox --noconfirm --needed
        pacman -S pcmanfm --noconfirm --needed
        # pacman -S lxterminal --noconfirm --needed
        # pacman -S xterm --noconfirm --needed
        # pacman -S gnome-terminal --noconfirm --needed
        # sed -i 's/^# \(session.*startlxde$\)/\1/' /etc/lxdm/lxdm.conf
    fi
    read -p "Install Cinnamon ?(y/N) " cinnamon
    if [[ "$cinnamon" == [yY] ]];then
        #安装cinnamon桌面环境
        pacman -S cinnamon --noconfirm --needed
        pacman -S gnome-terminal --noconfirm --needed
    fi

    read -p "Install KDE ? (y/N) " kde
    if [[ "$kde" == [yY] ]];then
        pacman -S plasma kde-applications --noconfirm --needed
        echo "exec startkde" >> /etc/X11/xinit/xinitrc

        echo 'export GTK_IM_MODULE=fcitx' >> ~/.xprofile
        echo 'export QT_IM_MODULE=fcitx' >> ~/.xprofile
        echo 'export XMODIFIERS="@im=fcitx"' >> ~/.xprofile
    fi
    read -p "Install fcitx ?(Y/n) " fcitx
    if [[ "$fcitx" != [nN] ]];then
        pacman -S fcitx-im --noconfirm --needed
        pacman -S fcitx-configtool --noconfirm --needed
        pacman -S fcitx-sunpinyin --noconfirm --needed
    fi

fi
