#!/bin/bash
if ! command -v apt-get >/dev/null 2>&1;then
    echo "Error: Not Debian!"
    exit 1
fi
if [[ $EUID != 0 ]];then
    echo "Error:need root priviledge!"
    exit 1
fi

installer=apt-get

#apt比apt-get更好用
if command -v apt > /dev/null 2>&1;then
    installer=apt
fi

basicApps="sudo vim vim-gtk tree curl screenfetch zsh openssh-server"
devApps="build-essential cmake clang  python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev"

$installer update -y
read -p "Install development tools (ie:clang python boost golang)? [y/N] " -t 3 installDev
read -p "Setup swap? [Y/n]" -t 3 setupSwap
read -p "Whom to be add to sudo group?" -t 3 sudoer

#TODO check $sudoer existence. if $sudoer does not exist?
if [[ -n "$sudoer" ]];then
    adduser $sudoer sudo
fi

for app in ${basicApps};do
    $installer install $app -y
done

if [[ "$installDev" == [yY] ]];then
    for app in ${devApps};do
        $installer install $app -y
    done
fi


if [[ "$setupSwap" != [nN] ]];then
    SWAP=/var/swap.img
    dd if=/dev/zero of="$SWAP" bs=1024k count=1000
    chmod 0600 "$SWAP"
    mkswap "$SWAP"
    swapon "$SWAP"
    echo "$SWAP none swap sw 0 0">>/etc/fstab
fi

read -p "set iptables?[Y/n]: " setIptables
if [[ "$setIptables" != [nN] ]];then
    iptablesRulesFile=/etc/iptables-rules
    cat > "$iptablesRulesFile" <<-EOF
    *filter
    :INPUT DROP [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    -A INPUT -i lo -j ACCEPT
    -A INPUT -p icmp -j ACCEPT

    #SSH port
    -A INPUT -p tcp --dport 22 -j ACCEPT

    #Shadowsocks port
    -A INPUT -p tcp --dport 29573 -j ACCEPT
    -A INPUT -p tcp --dport 39033 -j ACCEPT
    -A INPUT -p tcp --dport 49682 -j ACCEPT
    -A INPUT -p tcp --dport 8387 -j ACCEPT
    -A INPUT -p tcp --dport 65454 -j ACCEPT
    -A INPUT -p tcp --dport 3001 -j ACCEPT
    -A INPUT -p tcp --dport 5050 -j ACCEPT

    #otherRule begin
    #http port
    -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
    #https port
    -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT

    ##the following four rules are proxy basic for redirect
    #http port
    -A INPUT -p tcp -m tcp --sport 80 -j ACCEPT
    #https port
    -A INPUT -p tcp -m tcp --sport 443 -j ACCEPT
    #DNS port
    -A INPUT -p tcp -m tcp --sport 53 -j ACCEPT
    -A INPUT -p udp -m udp --sport 53 -j ACCEPT
    #otherRule end
    COMMIT
    EOF
    iptablesScript=/etc/network/if-up.d/enableIptables.sh
    cat > "$iptablesScript" <<-EOF
    #!/bin/bash
    /sbin/iptables-restore "$iptablesRulesFile"
    EOF
    chmod +x "${iptablesScript}"
fi
