#!/bin/bash
if ! command -v apt-get >/dev/null 2>&1;then
    echo "Error: Not Debian!"
    exit 1
fi
if [[ $EUID != 0 ]];then
    echo "Error:need root priviledge!"
    exit 1
fi

installer=apt-get

#apt比apt-get更好用
if command -v apt > /dev/null 2>&1;then
    installer=apt
fi

basicApps="sudo vim vim-gtk tree curl build-essential screenfetch zsh"
devApps="cmake clang  python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev"

$installer update -y
read -p "Install development tools? [y/N] " -t 3 installDev
read -p "Setup swap? [Y/n]" -t 3 setupSwap
for tool in ${basicApps};do
    $installer install $tool -y
done

if [[ "$installDev" == [yY] ]];then
    for tool in ${devApps};do
        $installer install $tool -y
    done
fi

if [[ "$setupSwap" != [nN] ]];then
    SWAP=/var/swap.img
    dd if=/dev/zero of="$SWAP" bs=1024k count=1000
    chmod 0600 "$SWAP"
    mkswap "$SWAP"
    swapon "$SWAP"
    echo "$SWAP none swap sw 0 0">>/etc/fstab
fi
